name: v8

on:
  push:
    branches: [ main ]
    paths:
      - "version"
      - "fyne-gui/version"
  workflow_dispatch: {}

jobs:
  linux-build:
    runs-on: ubuntu-22.04
    steps:
      
    - name: clone gv8
      run: |
        mkdir mcs && cd mcs
        wget https://github.com/LiteLDev/LiteLoaderBDS/raw/develop/scripts/install.sh && sh install.sh
        cd ..
        
    - name: Archive binaries
      run: |
        tar -czf mcs.tar.gz mcs

    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: mcs.rel
        files: |
          mcs.tar.gz
